// Obfuscated payload
const secretPayload = "dGhpcyBpcyBhIHZlcnkgbG9uZyBiYXNlNjQgc3RyaW5nIHRoYXQgc2hvdWxkIGJlIGZsYWdnZWQgYXMgYSBwb3RlbnRpYWwgbWFsaWNpb3VzIHBheWxvYWQgYmVjYXVzZSBpdCBleGNlZWRzIHRoZSBkZWZhdWx0IDIwMCBjaGFyYWN0ZXIgbGltaXQgYW5kIGNvbnRhaW5zIHJhbmRvbSBsb29raW5nIGJpbmFyeSBkYXRh";
